apiVersion: apps/v1
kind: Deployment

metadata:
  name: sandbox-server-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sandbox-server

  template:
    metadata:
      labels:
        app: sandbox-server

    spec:
      serviceAccountName: resource-manager

      containers:
        - name: sandbox-server
          image: sandbox-server:v1
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          ports:
            - containerPort: 3000