FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl ca-certificates

RUN curl -LO "https://dl.k8s.io/release/v1.36.1/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]